// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SupermarketWebApi;
using System;

namespace SupermarketWebApi.Migrations
{
    [DbContext(typeof(SupermarketContext))]
    partial class SupermarketContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SupermarketWebApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Price");

                    b.HasKey("ProductId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SupermarketWebApi.Models.StaffMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("SupermarketId");

                    b.HasKey("Id");

                    b.HasIndex("SupermarketId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("SupermarketWebApi.Models.Supermarket", b =>
                {
                    b.Property<int>("SupermarketId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("NumberOfStaff");

                    b.HasKey("SupermarketId");

                    b.ToTable("Supermarkets");
                });

            modelBuilder.Entity("SupermarketWebApi.Models.SupermarketStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NumberInStock");

                    b.Property<int>("ProductId");

                    b.Property<int>("SupermarketId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupermarketId");

                    b.ToTable("SupermarketStocks");
                });

            modelBuilder.Entity("SupermarketWebApi.Models.StaffMember", b =>
                {
                    b.HasOne("SupermarketWebApi.Models.Supermarket", "Supermarket")
                        .WithMany("StaffMembers")
                        .HasForeignKey("SupermarketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SupermarketWebApi.Models.SupermarketStock", b =>
                {
                    b.HasOne("SupermarketWebApi.Models.Product", "Product")
                        .WithMany("SupermarketStocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SupermarketWebApi.Models.Supermarket", "Supermarket")
                        .WithMany("SupermarketStocks")
                        .HasForeignKey("SupermarketId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
